"use client";

// import type { Metadata } from "next";
import Link from "next/link";
import { Ovo, Mulish } from "next/font/google";
import "./globals.css";
import { type ReactNode, useState } from "react";
import { usePathname } from "next/navigation";

const ovo = Ovo({
  variable: "--font-ovo",
  subsets: ["latin"],
  weight: "400",
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function NavElement({
  paths,
  path,
  children,
}: {
  paths: string[];
  path: string;
  children: ReactNode;
}) {
  const style = paths.includes(path)
    ? "underline text-(--Colour-Font-Primary)"
    : "text-(--Colour-Font-Tertiary)";
  return (
    <div
      className={`flex justify-center items-center py-[24px] ${style} hover:text-(--Colour-Font-Primary) transition ease-in-out duration-300`}
    >
      {children}
    </div>
  );
}

// TO-DO: Build drop-down for nav-bar
function NavProject({ href, children }: { href: string; children: ReactNode }) {
  return (
    <Link
      href={href}
      className="flex self-stretch justify-center items-center px-[32px] py-[16px] 
      font-[Mulish] text-[0.75rem]/[1rem] tracking-[0.96px] uppercase text-(--Colour-Font-Tertiary)
       bg-white hover:bg-[#EDEDED] hover:text-(--Colour-Font-Secondary) active:bg-[#EDEDED] active:text-(--Colour-Font-Secondary) transition ease-in-out duration-300"
    >
      <div className="no-underline">{children}</div>
    </Link>
  );
}

function DropDown() {
  return (
    <ul className="absolute top-[96px] right-0 md:right-auto w-[256px] border border-solid border-[#EDEDED] ">
      <li>
        <NavProject href="/work/snuggle">snuggle</NavProject>
      </li>
      <li>
        <NavProject href="/work/apothecare">apothecare</NavProject>
      </li>
      <li>
        <NavProject href="/work/myanimelist">myanimelist</NavProject>
      </li>
    </ul>
  );
}

function NavBar() {
  const path = usePathname();
  const [isDropdownVisible, setDropdownVisible] = useState(false);

  function handleMouseEnter() {
    setDropdownVisible(true);
  }

  function handleMouseLeave() {
    setDropdownVisible(false);
  }

  function onClick() {
    setDropdownVisible(false);
  }

  // TO-DO: implement dropdown click
  // function handleDropDownClick() {
  //   setDropdownVisible(true);
  // };

  return (
    <div className="w-full flex self-stretch px-8 md:px-16 lg:px-auto pt-[24px] justify-center sticky z-10 top-0 bg-white shadow-[2px_4px_8px_0px_rgba(107,84,39,0.10)]">
      <div className="flex flex-row flex-1 self-stretch justify-between items-center max-w-[928px]">
        <div className="">
          <p className="text-(--Colour-Font-Secondary)">evelyn law</p>
        </div>
        <nav className="self-stretch flex flex-row justify-start items-center gap-[24px] lg:gap-[48px]">
          <NavElement paths={["/"]} path={path}>
            <Link href="/">home</Link>
          </NavElement>
          <div
            onMouseEnter={handleMouseEnter}
            onMouseLeave={handleMouseLeave}
            onClick={onClick}
          >
            <NavElement
              paths={["/work/snuggle", "/work/apothecare", "/work/myanimelist"]}
              path={path}
            >
              work
              {isDropdownVisible && <DropDown />}
            </NavElement>
          </div>
        </nav>
      </div>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ovo.variable} ${mulish.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
