"use client";

import type { Metadata } from "next";
import Link from "next/link";
import { Ovo, Mulish } from "next/font/google";
import "./globals.css";
import { type ReactNode, useState } from "react";

const ovo = Ovo({
  variable: "--font-ovo",
  subsets: ["latin"],
  weight: "400",
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function NavElement({
  nav,
  link,
  onClick,
  children,
}: {
  nav: string;
  link: string;
  onClick: (navLocation: string) => void;
  children: ReactNode;
}) {
  const style =
    nav === link
      ? "underline text-(--Colour-Font-Primary)"
      : "text-(--Colour-Font-Tertiary)";
  return (
    <div
      className={`flex justify-center items-center py-[24px]  px-[48px]  ${style} hover:text-(--Colour-Font-Primary) transition ease-in-out duration-300`}
      onClick={() => onClick(link)}
    >
      {children}
    </div>
  );
}

// TO-DO: Build drop-down for nav-bar
function NavProject({
  onClick,
  href,
  children,
}: {
  onClick: (navLocation: string) => void;
  href: string;
  children: ReactNode;
}) {
  return (
    <Link
      href={href}
      className="flex self-stretch justify-center items-center px-[32px] py-[16px] 
      font-[Mulish] text-[0.75rem]/[1rem] tracking-[0.96px] uppercase text-(--Colour-Font-Tertiary)
       bg-white hover:bg-[#EDEDED]"
      onClick={() => onClick("work")}
    >
      <div className="no-underline">{children}</div>
    </Link>
  );
}

function DropDown({ onClick }: { onClick: (navLocation: string) => void }) {
  return (
    <ul className="absolute  w-[256px] border border-solid border-[#EDEDED] ">
      <li>
        <NavProject onClick={onClick} href="/work/snuggle">
          snuggle
        </NavProject>
      </li>
      <li>
        <NavProject onClick={onClick} href="/work/apothecare">
          apothecare
        </NavProject>
      </li>
      <li>
        <NavProject onClick={onClick} href="/work/myanimelist">
          myanimelist
        </NavProject>
      </li>
    </ul>
  );
}

function NavBar() {
  const [nav, setNav] = useState("home");
  const [isDropdownVisible, setDropdownVisible] = useState(false);

  function handleNavClick(navLocation: string) {
    setNav(navLocation);
  }
  function handleMouseEnter() {
    setDropdownVisible(true);
  }

  function handleMouseLeave() {
    setDropdownVisible(false);
  }

  // TO-DO: implement dropdown click
  // function handleDropDownClick() {
  //   setDropdownVisible(true);
  // };

  return (
    <div className="w-[100vw] px-8 md:px-16 lg:px-[256px] pt-[24px] sticky top-0 bg-white shadow-[2px_4px_8px_0px_rgba(107,84,39,0.10)] inline-flex justify-between items-center">
      <div className="justify-start">
        <p className="text-(--Colour-Font-Secondary)">evelyn law</p>
      </div>
      <nav className="self-stretch inline-flex justify-start items-center gap-[24px]">
        <NavElement nav={nav} link="home" onClick={handleNavClick}>
          <Link href="/">home</Link>
        </NavElement>
        <div onMouseEnter={handleMouseEnter} onMouseLeave={handleMouseLeave}>
          <NavElement nav={nav} link="work" onClick={handleNavClick}>
            work
          </NavElement>
          {isDropdownVisible && <DropDown onClick={handleNavClick} />}
        </div>
        {/* <NavElement
          nav={nav}
          link="snuggle"
          onClick={handleClick}
          href="/work/snuggle"
        >
          snuggle
        </NavElement>
        <NavElement
          nav={nav}
          link="apothecare"
          onClick={handleClick}
          href="/work/apothecare"
        >
          apothecare
        </NavElement>
        <NavElement
          nav={nav}
          link="myanimelist"
          onClick={handleClick}
          href="/work/myanimelist"
        >
          myanimelist
        </NavElement> */}
      </nav>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ovo.variable} ${mulish.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
