import type { Metadata } from "next";
import { Ovo, Mulish } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/NavBar";

const ovo = Ovo({
  variable: "--font-ovo",
  subsets: ["latin"],
  weight: "400",
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ovo.variable} ${mulish.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
