"use client";

import type { Metadata } from "next";
import Link from "next/link";
import { Ovo, Mulish } from "next/font/google";
import "./globals.css";
import { type ReactNode, useState } from "react";

const ovo = Ovo({
  variable: "--font-ovo",
  subsets: ["latin"],
  weight: "400",
});

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function NavElement({
  nav,
  link,
  onClick,
  href,
  children,
}: {
  nav: string;
  link: string;
  onClick: (navLocation: string) => void;
  href: string;
  children: ReactNode;
}) {
  const style =
    nav === link
      ? "underline text-(--Colour-Font-Primary)"
      : "text-(--Colour-Font-Tertiary)";
  return (
    <div
      className={`flex justify-center items-center h-[24px] ${style} hover:text-(--Colour-Font-Primary) transition ease-in-out duration-300`}
      onClick={() => onClick(link)}
    >
      <Link href={href}>{children}</Link>
    </div>
  );
}

// TO-DO: Build drop-down for nav-bar
function NavProject({
  onClick,
  href,
  children,
}: {
  onClick: (navLocation: string) => void;
  href: string;
  children: ReactNode;
}) {
  return (
    <div className="" onClick={() => onClick("work")}>
      <Link href={href}>{children}</Link>
    </div>
  );
}

function NavBar() {
  const [nav, setNav] = useState("home");
  function handleClick(navLocation: string) {
    setNav(navLocation);
  }
  return (
    <div className="w-[100vw] px-8 md:px-16 lg:px-[256px] pt-[48px] pb-[24px] sticky top-0 bg-white shadow-[2px_4px_8px_0px_rgba(107,84,39,0.10)] inline-flex justify-between items-center overflow-hidden">
      <div className="justify-start">
        <p className="text-(--Colour-Font-Secondary)">evelyn law</p>
      </div>
      <nav className="self-stretch inline-flex justify-start items-center gap-24">
        <NavElement nav={nav} link="home" onClick={handleClick} href="/">
          home
        </NavElement>
        <NavElement
          nav={nav}
          link="snuggle"
          onClick={handleClick}
          href="/work/snuggle"
        >
          snuggle
        </NavElement>
        <NavElement
          nav={nav}
          link="apothecare"
          onClick={handleClick}
          href="/work/apothecare"
        >
          apothecare
        </NavElement>
        <NavElement
          nav={nav}
          link="myanimelist"
          onClick={handleClick}
          href="/work/myanimelist"
        >
          myanimelist
        </NavElement>
      </nav>
    </div>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${ovo.variable} ${mulish.variable} antialiased`}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
